// BUILDING FUNCTIONS
export const GET_BUILDINGS = "GET_BUILDINGS";
export const ADD_BUILDING = "ADD_BUILDING";
export const DELETE_BUILDING = "DELETE_BUILDING";
export const UPDATE_BUILDING = "UPDATE_BUILDING";
export const UPDATE_BSTATE = "UPDATE_BSTATE";

// WATERTOWER FUNCTIONS
export const GET_WATERTOWERS = "GET_WATERTOWERS";
export const ADD_WATERTOWER = "ADD_WATERTOWER";
export const DELETE_WATERTOWER = "DELETE_WATERTOWER";
export const UPDATE_WATERTOWER = "UPDATE_WATERTOWER";
export const UPDATE_BUDGET = "UPDATE_BUDGET";

// COMPANY FUNCTIONS
export const GET_COMPANIES = "GET_COMPANIES";
export const ADD_COMPANY = "ADD_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";

// EXPENSE FUNCTIONS
export const GET_EXPENSES = "GET_EXPENSES";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const UPDATE_EXPENSE_PROJECT_NAME = "UPDATE_EXPENSE_PROJECT_NAME";

// BUILDINGSTEPS FUNCTION
export const GET_BUILDING_STEPS = "GET_BUILDING_STEPS";
export const ADD_BUILDING_STEPS = "ADD_BUILDING_STEPS";
export const UPDATE_BUILDING_STEPS = "UPDATE_BUILDING_STEPS";

// WATERTOWER STEPS
export const GET_WATERTOWER_STEPS = "GET_WATERTOWER_STEPS";
export const ADD_WATERTOWER_STEPS = "ADD_WATERTOWER_STEPS";
export const UPDATE_WATERTOWER_STEPS = "UPDATE_WATERTOWER_STEPS";

//COMMON BETWEEN FUNCTIONS
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_COMPANY_NAME = "UPDATE_COMPANY_NAME";
export const UPDATE_PRB = "UPDATE_PRB";

// AUTH FUNCTIONS
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// USERS FUNCTIONS
export const GET_USERS = "GET_USERS";
export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER = "UPDATE_USER";
